# Generated by Django 5.0.6 on 2024-07-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
