# Generated by Django 5.0.6 on 2024-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_civil_status_item_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gsis_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
