# Generated by Django 5.0.6 on 2024-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_item_gsis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gsis_id',
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
