# Generated by Django 5.0.6 on 2024-07-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item_blood_type_item_gsis_id_item_pag_ibig_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
