# Generated by Django 5.0.6 on 2024-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_agency_employee_item_citizenship_item_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
